export const skillsData = [
  {
    title: "AI/ML",
    technologies: ["Python", "TensorFlow", "scikit-learn"],
    description: "Building and deploying machine learning models with state-of-the-art frameworks.",
    animationType: "neuralNetwork",
    bgColor: "from-blue-500 to-violet-500",
    iconColor: "text-blue-500",
    darkIconColor: "dark:text-blue-400",
  },
  {
    title: "Data Science",
    technologies: ["Python", "SQL", "Pandas", "Matplotlib"],
    description: "Extracting insights from data through analysis, visualization, and statistical modeling.",
    animationType: "charts",
    bgColor: "from-green-500 to-teal-500",
    iconColor: "text-green-500",
    darkIconColor: "dark:text-green-400",
  },
  {
    title: "Generative AI",
    technologies: ["OpenAI API", "HuggingFace", "LangChain"],
    description: "Creating content generation systems using advanced AI techniques and tools.",
    animationType: "chatbot",
    bgColor: "from-purple-500 to-pink-500",
    iconColor: "text-purple-500",
    darkIconColor: "dark:text-purple-400",
  },
  {
    title: "Agentic AI",
    technologies: ["LangChain", "AutoGPT", "Multi-Agent Systems"],
    description: "Exploring autonomous decision-making models and intelligent agents with reasoning capabilities.",
    animationType: "agenticAI",
    bgColor: "from-pink-500 to-purple-500",
    iconColor: "text-pink-500",
    darkIconColor: "dark:text-pink-400",
  },
  {
    title: "DSA in C++",
    technologies: ["C++", "LeetCode"],
    description: "Implementing efficient algorithms and data structures for complex problem solving.",
    animationType: "graph",
    bgColor: "from-red-500 to-orange-500",
    iconColor: "text-red-500",
    darkIconColor: "dark:text-red-400",
  },
  {
    title: "UI/UX Design",
    technologies: ["Figma", "Adobe XD"],
    description: "Creating intuitive and visually appealing user interfaces and experiences.",
    animationType: "wireframe",
    bgColor: "from-pink-500 to-rose-500",
    iconColor: "text-pink-500",
    darkIconColor: "dark:text-pink-400",
  },
  {
    title: "Blockchain",
    technologies: ["Solidity", "Ethereum"],
    description: "Developing decentralized applications and smart contracts on blockchain platforms.",
    animationType: "blockchain",
    bgColor: "from-blue-500 to-cyan-500",
    iconColor: "text-blue-500",
    darkIconColor: "dark:text-blue-400",
  },
  {
    title: "App Development",
    technologies: ["Flutter", "Android Studio"],
    description: "Building cross-platform mobile applications with modern frameworks.",
    animationType: "mobileApp",
    bgColor: "from-cyan-500 to-sky-500",
    iconColor: "text-cyan-500",
    darkIconColor: "dark:text-cyan-400",
  },
  {
    title: "Cybersecurity",
    technologies: ["Python", "Wireshark", "CEH/OSCP"],
    description: "Implementing security measures and identifying vulnerabilities in systems.",
    animationType: "security",
    bgColor: "from-emerald-500 to-green-500",
    iconColor: "text-emerald-500",
    darkIconColor: "dark:text-emerald-400",
  },
  {
    title: "API Development",
    technologies: ["Node.js", "FastAPI", "Postman"],
    description: "Designing and implementing robust and scalable API endpoints and services.",
    animationType: "api",
    bgColor: "from-amber-500 to-yellow-500",
    iconColor: "text-amber-500",
    darkIconColor: "dark:text-amber-400",
  },
  {
    title: "System Design",
    technologies: ["System architecture", "Lucidchart"],
    description: "Planning and architecting scalable and efficient system structures.",
    animationType: "systemDesign",
    bgColor: "from-teal-500 to-emerald-500",
    iconColor: "text-teal-500",
    darkIconColor: "dark:text-teal-400",
  },
  {
    title: "Blender",
    technologies: ["Blender 3D", "Python"],
    description: "Creating 3D models, animations, and visual effects for various applications.",
    animationType: "3dObject",
    bgColor: "from-orange-500 to-amber-500",
    iconColor: "text-orange-500",
    darkIconColor: "dark:text-orange-400",
  },
  {
    title: "AWS",
    technologies: ["EC2", "S3", "Lambda"],
    description: "Deploying and managing cloud infrastructure and services on Amazon Web Services.",
    animationType: "cloud",
    bgColor: "from-yellow-500 to-orange-500",
    iconColor: "text-yellow-500",
    darkIconColor: "dark:text-yellow-400",
  },
  {
    title: "Web Development",
    technologies: ["HTML", "CSS", "JavaScript", "React"],
    description: "Building modern, responsive web applications with the latest technologies.",
    animationType: "components",
    bgColor: "from-blue-500 to-indigo-500",
    iconColor: "text-blue-500",
    darkIconColor: "dark:text-blue-400",
  },
  {
    title: "DevOps",
    technologies: ["Docker", "Jenkins", "GitHub Actions"],
    description: "Implementing CI/CD pipelines and automating deployment processes.",
    animationType: "pipeline",
    bgColor: "from-indigo-500 to-violet-500",
    iconColor: "text-indigo-500", 
    darkIconColor: "dark:text-indigo-400",
  },
  {
    title: "Cloud Computing",
    technologies: ["AWS", "Azure", "GCP"],
    description: "Deploying and managing applications across multiple cloud platforms.",
    animationType: "cloudServices",
    bgColor: "from-sky-500 to-blue-500",
    iconColor: "text-sky-500",
    darkIconColor: "dark:text-sky-400",
  },
  {
    title: "Software Engineering",
    technologies: ["Java", "SQL", "DBMS", "OS"],
    description: "Developing robust software solutions following best engineering practices.",
    animationType: "flowchart",
    bgColor: "from-red-500 to-rose-500",
    iconColor: "text-red-500",
    darkIconColor: "dark:text-red-400",
  },
  {
    title: "Internship Prep",
    technologies: ["Resume", "GitHub", "LeetCode"],
    description: "Preparing for technical interviews and career opportunities in tech.",
    animationType: "checklist",
    bgColor: "from-green-500 to-lime-500",
    iconColor: "text-green-500",
    darkIconColor: "dark:text-green-400",
  },
  {
    title: "Hackathon Prep",
    technologies: ["Figma", "Teamwork tools"],
    description: "Planning and executing innovative projects in time-constrained environments.",
    animationType: "collaboration",
    bgColor: "from-violet-500 to-purple-500",
    iconColor: "text-violet-500",
    darkIconColor: "dark:text-violet-400",
  }
]